name: Generate Static Links

on:
  push:
    branches:
      - main

jobs:
  generate-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate links
      shell: bash
      run: |
        shopt -s globstar
        links=""
        for file in images/**/*.{png,jpg,jpeg,svg,webp,ico}; do
          url="https://cdn.statically.io/gh/${{ github.repository }}/main/$(echo $file | sed 's/images\///g')"
          links="${links}- $(basename $file)\n  $url\n"
        done
        echo "$links" > links.md

    - name: Commit and push changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add links.md
        git commit -m "Add links.md"
        git push origin HEAD