on:
  push:
    branches:
      - main

jobs:
  generate-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate links
      shell: bash
      run: |
        shopt -s globstar
        # Start the table with headers
        links="| Name | URL |\n| ---- | --- |\n"
        for file in images/**/*.{png,jpg,jpeg,svg,webp,ico,gif,pdf}; do
          url="https://cdn.statically.io/gh/${{ github.repository }}/main/$file"
          # Append each file and URL as a row in the table
          links="${links}| $(basename $file) | $url |\n"
        done
        echo -e "$links" > links.md

    - name: Commit and push changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Statically Workflow"
        git add links.md
        git commit -m "Add links.md in table format"
        git push origin HEAD
